### ISSUE TITLE
Missing version: cannot install from repository

### ISSUE THREAD

**Issue by aumeunier** [supnate/rekit#101]
I'd like to update to the latest version of rekit, which is not available on npm (yet?)
But I can't seem to update it from the github repository, which makes sense as I don't see the version value in the package.json file
```
npm install git+https://github.com/supnate/rekit.git -g
npm ERR! Can't install git+https://github.com/supnate/rekit.git#3e0c631d259979205b8a7a001cb040984b78ef74: Missing package version
```

**Comment by supnate** [comment]
1. The latest version is just as in the npm (rekit, rekit-core and rekit-studio)
2. The repo is managed by [yarn workspace](https://yarnpkg.com/lang/en/docs/workspaces/) so yo need yarn to install, so you can't use npm to install deps.
