### ISSUE TITLE
rekit create: error: Unrecognized arguments: [--sass] [--clean]

### ISSUE THREAD

**Issue by mrassili** [supnate/rekit#102]
I followed the instructions on the Readme and I've got this error on terminal

`rekit create: error: Unrecognized arguments: [--sass] [--clean].`

**Comment by supnate** [comment]
Version? Full command? OS?

**Comment by supnate** [comment]
Maybe you have type the command like this:
```
rekit create app [--clean] [--sass]
```
It should be:
```
rekit create app --clean --sass
```

**Comment by rosariogueli** [comment]
I've just run the following but the projects look identical, I was expecting one of them without examples  folder but both of them have it. 
rekit create myapp
rekit create myapp --clean

**Comment by supnate** [comment]
@rosariogueli `--clean` argument was removed because removing example code is very simple. You can use `rekit rm feature examples` command or using Rekit Studio to remove examples code.

However it will be added back in the coming 3.0.

**Comment by rosariogueli** [comment]
@supnate Thank you. I wasn't aware of it. I really can't wait to work with the new 3.0. Do you have an estimated time of release?

**Comment by supnate** [comment]
You can try 3.0 at https://github.com/rekit/rekit-app/releases if you use a Mac.
Otherwise, use 3.0 beta via cli:
```
> npm install -g rekit@next rekit-studio@next
> rekit create my-app
> cd my-app
> npm install
> rekit-studio
```

**Comment by rosariogueli** [comment]
Yes I use a Mac. Thank you so much! It looks brilliant! What are the main differences with Rekit 2? I can see it is back compatible with old projects which is sweet!
