### ISSUE TITLE
Adding proxy in package.json does not route requests to the specified server 

### ISSUE THREAD

**Issue by CriPstian** [supnate/rekit#103]
Hello,

I looked around the issues, and could not find this anywhere. I just created a new application using rekit. In development I want to proxy all the http fetches to the same machine on port 5000, since I have a flask server running there.
Added a proxy in `package.json`:

`"proxy": "http://localhost: 5000"`

Since I used this with `create-react-app` I wonder if it is something I missed using this.

**Comment by supnate** [comment]
You need to put this under `rekit` section:
```
"rekit": {
  ...
  "proxy": "http://localhost: 5000"
}
```

**Comment by CriPstian** [comment]
That I did not know. I will try this ASAP. Thank you
