### ISSUE TITLE
rekit yarn build: Page Not Found

### ISSUE THREAD

**Issue by zzh1991** [supnate/rekit#118]
When I have finish built, it always show that page not found.
<img width="1346" alt="error" src="https://user-images.githubusercontent.com/14806009/39082969-6c606088-458e-11e8-9b56-87ed565bad51.png">

It is OK when yarn start.

The newest rekit version also has this problem.

**Comment by supnate** [comment]
Just tried the latest Rekit, I can't reproduce the issue. Could you please verify?

**Comment by zzh1991** [comment]
version @2.3.0
1. rekit create test
