### ISSUE TITLE
With Existing Project instructions - server.js missing ?

### ISSUE THREAD

**Issue by Serexx** [supnate/rekit#128]
This has really great potential, thanks for all the work putting it together!

The [How to use Rekit-Studio with an existing project](https://medium.freecodecamp.org/using-rekit-studio-in-an-existing-react-project-39713d9667b) mentions Rekit npm scripts being resident in **server.js** with the names
- startDevServer
- buildDevDll
- startStudioServer
 - startBuildServer

After using 
`npm Rekit create --clean my-clean-app` 

I can't find either server.js or the noted scripts anywhere, including in ./node_modules/rekit/

Are the instructions just out of date or am i missing something?

Thanks for you help!

**Comment by Serexx** [comment]
Solved... rather than be literal (long day) I engaged brain and tracked down the scripts actually in use, cleverly hidden in the 'Scripts' folder.

**Comment by supnate** [comment]
Yeah.. Sorry for the confusion. The project boilerplate was updated to Create React App after the article. So I should have updated it.
