### ISSUE TITLE
React router v4

### ISSUE THREAD

**Issue by saggiyogesh** [supnate/rekit#13]
Any plans to migrate the router to v4 ?

**Comment by supnate** [comment]
Yes. V4 is still alpha. We will migrate to it when it's GA.

**Comment by saggiyogesh** [comment]
It'll be easy to migrate the existing code?

**Comment by supnate** [comment]
Yes, the route config is well decoupled from other application logic.

**Comment by supnate** [comment]
Close this since v4 has been supported by Rekit 2.0.
