### ISSUE TITLE
how to redirect after login

### ISSUE THREAD

**Issue by tigrankhachikyan** [supnate/rekit#134]
Hello.

can you please suggest a right way to redirect after the successful login?
like I have `/login`  and after successful it should redirect user to `/app`

Thank you

**Comment by supnate** [comment]
You can use `src/common/history`.
```
import history from '../common/history';

// after login
history.replace('/app');
```

**Comment by tigrankhachikyan** [comment]
Thank you!

**Comment by danielo515** [comment]
That's fantastic. How can you perform the same operation to redirect the user in case it is not logged-in?
I mean, check the store, see the user is not logged in and redirect him. 
Maybe on the common reducer?
