### ISSUE TITLE
Migrating a project from Rekit v1 to Rekit v2

### ISSUE THREAD

**Issue by leandrown** [supnate/rekit#151]
Hello! I'm very excited with this project, but I'm a React/Rekit newbie.
I found some examples made with Rekit 1 and I didn't found anywhere how to migrate do Rekit v2.
Someone please can give me a light?

**Comment by supnate** [comment]
Thanks @leandrown , you can find Rekit 2 todomvc example at: https://github.com/supnate/rekit-todomvc . Because Rekit 1 has very few users so there's no migrate guide.
