### ISSUE TITLE
Two different layouts in App

### ISSUE THREAD

**Issue by PawanWagh** [supnate/rekit#160]
I've two different layouts like different header & footer if user is not logged in and different header, footer, and a left side panel if user is logged in.
I've created anonymous user layout in root App but i am confused how to achieve the same for logged in user so that i don't have import common components again and again.
Below is my features structure --> 
- Auth
- Common
- Dashboard
- Home ( this is where my common layout lies for anonymous user)
- Profile

I still have a doubt, if Auth feature deals with user authentication ( which means all auth related redux state lies in `this.props.auth` ) but then i need to access this state from dashboard feature ( or dashboard components ) then how would i do this ?

Thank you.

**Comment by PawanWagh** [comment]
I've modified App to connect with redux store and works exactly as i expected, 
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import {UHeader, UFooter, AHeader, AFooter} from './Header';

import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import * as actions from './redux/actions';

/*
  This is the root component of your app. Here you define the overall layout
  and the container of the react router.
  You should adjust it according to the requirement of your app.
*/
export class App extends Component {
  static propTypes = {
    children: PropTypes.node,
    home: PropTypes.object.isRequired,
    actions: PropTypes.object.isRequired,
    auth: PropTypes.object.isRequired,
  };

  static defaultProps = {
    children: '',
  };

  render() {
   const { auth } = this.props;
    return (
      <div className="home-app">
        {
              !auth.isSignedIn ? ( <UHeader /> ) : ( <AHeader /> )
        }
        <div className="page-container">{this.props.children}</div>
        {
              !auth.isSignedIn ? ( <UFooter /> ) : ( <AFooter /> )
        }
      </div>
    );
  }
}

/* istanbul ignore next */
function mapStateToProps(state) {
  return {
    home: state.home,
    auth: state.auth
  };
}

/* istanbul ignore next */
function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators({ ...actions }, dispatch),
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

but is this a standard practice of achieving this or there's a more standard way ?

**Comment by supnate** [comment]
Yes, this is the correct way to share data among features.

**Comment by PawanWagh** [comment]
@supnate : thanks. also thank you for sharing such a great tool with us.
