### ISSUE TITLE
Possible to use with non-react projects via plugins?

### ISSUE THREAD

**Issue by kosirm** [supnate/rekit#162]
Hi, I really like this project, I think that it is amazing!
Currently I'm developing something with [PWA Starter Kit](https://polymer.github.io/pwa-starter-kit/) from Google Polymer team, and since it relies on redux in a similar way as this project does, I wonder if it would be possible to use rekit project for PWA Starter Kit development (which is [lit-html](https://polymer.github.io/lit-html/) based, not react-based) via (custom) rekit plugins, or to express it differently, does rekit plugins functionality allow to build non-react projects?

**Comment by supnate** [comment]
Hi @kosirm ,

Yes it's possible. Actually the next 3.0 release I'm currently working on is mainly to provide a common IDE for any type of project. But it will be release about 1 month later. In master branch `packages/rekit-studio/src/features/plugin-cra` is used for React project. And `plugin-node` is for node application. You may take a look but currently no docs about it. After the next 3.0 release I will write detail docs about it. So you may need to wait for it.

In general, the common IDE provide easy extension mechanism for organizing source files, provide base diagrams, extend element types (component, action, etc...).

**Comment by kosirm** [comment]
Thanks, @supnate, that's fantastic information! I'm looking forward to learning and using this project. I will close this because I got all the information I need.
