### ISSUE TITLE
Cannot destructure property `compile` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by schatzdesigns** [supnate/rekit#169]
I keep receiving this error when i do an npm start or yarn start.

`Cannot destructure property 'compile' of 'undefined' or 'null'`

Steps to reproduce:
1. rekit create demo-app
2. cd demo-app
3. yarn install/npm install
4. yarn upgrade
5. yarn start

![sketch](https://user-images.githubusercontent.com/3469965/48201980-b9ef9d80-e374-11e8-9eaf-b6d7322d8108.png)

Any help would be appreciated.

**Comment by YC-L** [comment]
Maybe because of the high version of webpack-dev-server.
Try this command ⬇
npm install -D webpack-dev-server@3.0.0

**Comment by cuifuan** [comment]
> Maybe because of the high version of webpack-dev-server.
> Try this command ⬇
> npm remove webpack-dev-server
> npm install -D webpack-dev-server@2.9.1
> 
> I resolve the question by the following procedure :
> 
> 1. cd "your project directory"
> 2. rm -rf node_modules
> 3. change the version of "webpack-dev-server" to 2.9.1 in
>    the file "package.json",
> 4. cnpm install (you just use npm install maybe)


### very good ! Thanks !

**Comment by Thebarda** [comment]
Rekit doesn't support natively webpack 4.
In this issue, I gave a solution that allow Rekit to works with webpack 4 and webpack-dev-server 3

**Comment by schatzdesigns** [comment]
Resolved the issue when I downgraded the webpack-dev-server to a lower version
**Thanks!!!**

**Comment by WalkAlone0325** [comment]
very good！Thanks！I learned!
