### ISSUE TITLE
rekit studio package can not start with webpack v4

### ISSUE THREAD

**Issue by shengliangli** [supnate/rekit#178]
你好：
      我现在在做一个可视化构建react页面的工具，希望能够借助 rekit 的能力来把浏览器生成的 react 代码保存到项目中并进行编译。
    我 fork 了 rekit，并且尝试在本地启动 rekit-studio，在packages/rekit-studio/目录下运行：yarn run start，启动失败。
    更换 package 中的 webpack 版本到 3.x，启动正常

**Comment by shengliangli** [comment]
另外，请教一下在本地调试 rekit-studio 的方法，直接在 packages/rekit-studio/目录下运行：yarn run start 似乎有问题，浏览器报告无法访问 api/project-data 的错误，我在 start.js 中增加了启动rekitMiddleWare 的代码，然后 api/project-data 能够返回内容了，但是返回的内容和通过rekit 创建的应用中 同样的请求返回的内容相差很大，实在不知道是什么原因。
请不吝赐教，多谢多谢

**Comment by shengliangli** [comment]
thank you @Thebarda

**Comment by shengliangli** [comment]
I'm wrong. Branch 2.x is OK！
Sorry @Thebarda. What I want is run and modify rikit-studio alone.

**Comment by supnate** [comment]
你好 @shengliangli ，
刚好正在回复，你自己就发现了：-）。目前 master 是 3.0 的 branch，有很大重构。如果你要能本地运行，可以先用 2.x branch。而且目前 3.0 的 Rekit Studio 因为插件需求的技术原因，已经移动到单独的 repo： github.com/supate/rekit-studio 。我知道也有其它同学基于 Rekit Studio 做了 UI 设计工具，看来有这需求的也挺多：-）。后续有什么问题，欢迎继续提问。

**Comment by shengliangli** [comment]
多谢回复，以后有问题会继续请教。
rekit 确实非常好，再次致敬！
@supnate
