### ISSUE TITLE
Costum async-action template

### ISSUE THREAD

**Issue by nelreina** [supnate/rekit#19]
Hi , 

Is there a way that I can create a custom async-action template and hook it in rekit ?

**Comment by supnate** [comment]
Yes, it's super easy with Rekit 2.0 alpha.

`npm install rekit@2.0-alpha.3 -g`

Then in tools folder of the created project, create a folder named `plugins`, and create your plugin.

You could take a look at: https://github.com/supnate/rekit/tree/2.0.0-alpha.3/tools
It shows an example for creating async action with redux-saga.

However, though the plugin will be refactored later and it looks complicated, it's helpful for you to understand the plugin structure.

All you need is a `config.js` and `customAsync.js` for you case, I think.

Feel free to leave a comment if any question.

**Comment by nelreina** [comment]
I use rekit alpha.4 the last version linked to rekit@next. I guess it will work the same.

**Comment by supnate** [comment]
Yes, it's the same. I just forgot to add a tag for alpha.3.
