### ISSUE TITLE
rekit 3 和 rekite 2 差异大吗？现在创建项目应该用rekit3 吗

### ISSUE THREAD

**Issue by dingyiming** [supnate/rekit#192]
最近刚开始学习使用 rekit ，看到作者已经在更新 rekit 3.0 的 npm release 了
- 现在用 rekit3 创建项目是否合适？ 
- rekit3 创建项目后 没看到 rekit studio  启动信息，是还没有集成进来吗？

**Comment by supnate** [comment]
Rekit 3 现在可以用了，新项目最好用 Rekit 3 因为基于 Creact React App V2 所以 Babel, Webpack 之类都是最新的。
现在 rekit-core 和 rekit-studio 不再是新建项目的依赖。要启动 rekit studio 有两种方式：
1. npm install -g rekit-studio@next 然后在所建项目下运行 `> rekit-studio -p 6078` 会在6078 端口下运行 Rekit Studio，通过浏览器访问。
2. 如果是 Mac 可以下载桌面应用：https://github.com/rekit/rekit-app/releases

**Comment by dingyiming** [comment]
感谢，立马用起来，后续会有支持  react native  或者 vue 之类框架的计划吗？

**Comment by supnate** [comment]
嗯，正式发布后会支持更多项目类型，如果你用 Mac App 可以看到已经有相关入口。不过目前只有 rekit-react 项目类型可用。

**Comment by dingyiming** [comment]
好的，谢谢
