### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by nelreina** [supnate/rekit#2]
I get the following error when trying to use rekit.
running on MACOS 
`$ rekit app-name`

**Comment by supnate** [comment]
Thanks @nelreina for reporting the issue.
It's caused by crlf line ending checked in by windows system. Now fixed. Please run `npm update rekit -g` to fix. Sorry for the inconvenience.

**Comment by nelreina** [comment]
YEP 👍  It works! Tnxs for the quick fix!
