### ISSUE TITLE
cannot find webpack-bundle-analyzer in package.json

### ISSUE THREAD

**Issue by seap** [supnate/rekit#22]
for v2.0, cannot find module 'webpack-bundle-analyzer'

`npm i webpack-bundle-analyzer --save-dev`

**Comment by supnate** [comment]
Thanks for reporting, it will be fixed in the next version.

**Comment by seap** [comment]
when will be the official v2.0 release?

**Comment by supnate** [comment]
About two weeks later.

**Comment by seap** [comment]
thanks for your quick reply. 
I like your portal design very much, add component template quickly. 
I have some questions as below:
1. Is there any way to change the template?
I found it is be maintained in Rekit Core. `rekit-core/templates/*.js`
I want to change some coding style
e.g.
```
static propTypes = {
    ${_.camelCase(feature)}: PropTypes.object.isRequired,
    actions: PropTypes.object.isRequired,
  };

==> 

${_.camelCase(feature)}.propTypes = {
}

${_.camelCase(feature)}.defaultProps = {
}

```

2. encapsulate the page with folder, including style, image and ....
e.g.
|-- features
|    |    |    |-- wallet
|    |    |    |    +-- redux
|    |    |    |    |-- HomePage
|    |    |    |    |    |-- index.js
|    |    |    |    |    |-- main.scss
|    |    |    |    |    |-- banner.png
|    |    |    |    |-- route.js
|    |    |    |    |-- ...

3. some suggestions
```
// support import css by each page or module, and extract by extract-text-webpack-plugin
{
          test: /\.scss$/,
          loader: 'style-loader!css-loader?sourceMap&modules=true&localIdentName=[local]_[hash:base64:5]!sass-loader?sourceMap'
}

// for production building, I hope to change the main.js by file hash, instead of timestamp
indexHtml = indexHtml.replace('/static/main.js', `/static/main.${timestamp}.js`);

```

thanks~

**Comment by supnate** [comment]
Thanks @seap .
1. You need to create a rekit plugin to modify the default template. Refer to https://github.com/supnate/rekit/blob/master/docs/plugin.md for the draft docs. And https://supnate.github.io/rekit-core/ for API reference. [rekit-plugin-redux-saga](https://github.com/supnate/rekit-plugin-redux-saga) is a sample. It modifies the async-action template. It's a bit complex now, maybe provide an easier way in future for template customization.

2. I prefer the current flatten folder structure and Rekit portal depends on the folder structure.

3. You can modify your webpack config or `build.js` for free to meet your requirement.

**Comment by supnate** [comment]
Fixed by beta 3.
