### ISSUE TITLE
Create an action for a class component through rekit3.0？

### ISSUE THREAD

**Issue by Jef-Z** [supnate/rekit#243]
I have an old project and I need to create an action，
`rekit add -t class action home/homeAction`,I get an action of type hooks  it doesn't work,
so `-t class` only works for component？
How can I create an action that can be used by a class component？

**Comment by supnate** [comment]
Actions doesn't have type concept, they can be used by both functional and class component. You don't need to specify -t option. What do you mean of not working?

**Comment by Jef-Z** [comment]
Hi!
A demo：
Run `rekit add  action pages/exportGifDate `,
get an action,
```
export function useExportGifDate() {
  const dispatch = useDispatch();
  const boundAction = useCallback((...params) => dispatch(exportGifDate(...params)), [dispatch]);
  return { exportGifDate: boundAction };
}
```
It's a hook，I can use it in function components。However, it cannot be used in class components。
I want an action that can be used in a class component.
What should I do？

**Comment by supnate** [comment]
Yes, it's an additional hook part in action. It's only for functional components. For class component, you don't use this `useXXX` function but need `connect`, for example, https://github.com/rekit/rekit-studio/blob/master/src/features/home/ElementPage.js

**Comment by Jef-Z** [comment]
Yes, it can be used in class components, but every time I need to delete the hooks part after the action is generated by the rekit. Is there a command that can directly generate actions without hooks?

**Comment by supnate** [comment]
hmm, there's no such a feature for now.. just manually remove it. and maybe you could try functional components for new code.

**Comment by Jef-Z** [comment]
hah，This project is relatively old.It is too expensive to migrate class components to function components. This project does not consider function components for the time being. Thanks for the answer!

**Comment by Z-J-Fei** [comment]
hah，This project is relatively old.It is too expensive to migrate class components to function components. This project does not consider function components for the time being. Thanks for the answer!
