### ISSUE TITLE
Some considerations: Redux first routing and sagas/async/await

### ISSUE THREAD

**Issue by loganpowell** [supnate/rekit#26]
Just curious what the next version of Rekit is shaping up to be and wanted to float a balloon on a couple of features:

1) It looks like your boilerplate app has a placeholder for sagas: features/home(andcommon)/redux/sagas.js are you going to implement sagas in the framework? Any thoughts on async/await?
2)  I also noticed you have some conflicts with the JSX implementation of React Router [here](http://rekit.js.org/docs/routing.html), have you considered a redux first router, e.g.: [router5](http://router5.github.io/) or [redux-little-router](https://github.com/FormidableLabs/redux-little-router)?

**Comment by supnate** [comment]
1. No, there will be no sagas by default in the framework. It will be removed in the release version. There is a plugin rekit-plugin-redux-saga. It does support async/await.
2. There's no conflict, it's just another JSON API of React Router. I've not been aware of 'redux first router' concept, will take a look.
