### ISSUE TITLE
how to use isDev in webpack-config , such as dll, test?

### ISSUE THREAD

**Issue by Gozeon** [supnate/rekit#29]
```javascript
type is one of [dev, dll, test, dist]
NOTE: for test, only module property is used.
```

**Comment by supnate** [comment]
`webpack-config.js` is used in `tools/server.js` which build for different targets like dist, dll, dev. `test` is useless for now, it uses webpack.test.config.js instead.

If you want to check is dev in your code, use `process.env.NODE_ENV`.
