### ISSUE TITLE
Error on 'rekit create myApp'

### ISSUE THREAD

**Issue by udiedrichsen** [supnate/rekit#32]
Hi,

I really like the rekit concept. I tried it today without success. 

rekit create myApp

Welcome to Rekit, now creating your project...
Copying files...
Getting the latest dependencies versions...
Failed to get dependencies. The project was not created. Please check and retry.
{ Error: getaddrinfo ENOTFOUND supnate.github.io supnate.github.io:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'supnate.github.io',
  host: 'supnate.github.io',
  port: 443 }

**Comment by supnate** [comment]
It looks like a network issue. Please check if you could access internet in your terminal.

**Comment by udiedrichsen** [comment]
Yes, thanks for the fast response. You are right. It was a connection issue in our company :-(
