### ISSUE TITLE
webpack devtool debug 问题

### ISSUE THREAD

**Issue by asmh1989** [supnate/rekit#35]
`rekit` 新建的工程能不能支持`chrome`下进行源码级别的断点调试. 类似`create-react-app`的生成的`demo`, 感觉会方便很多.

**Comment by supnate** [comment]
这必须已支持啊 😂 你可以确认下。在 Chrome 的 source tab 下，webpack:// . 路径下可以看到源码。你也可以在代码中插入 debugger 语句来加入断点。

**Comment by asmh1989** [comment]
@supnate 这个代码是生成过的不是源码

**Comment by supnate** [comment]
@asmh1989 哦，抱歉，理解错了。Rekit 现在使用的是 "eval" 级别的源码，这样开发时热更新速度比较快，所以看到的是 Babel 翻译过的代码，个人以为也可以理解并调试。如果习惯看原始的源码，可以在 webpack-config.js 文件中将 devtool: { dev: 'eval' } 改成 dev: 'source-map'，这样就能看到严格的源码了。具体的参数含义可以参考：https://webpack.js.org/configuration/devtool/

**Comment by asmh1989** [comment]
@supnate 好的, 谢谢. 确实可以. 一开始我以为要和`create-react-app` 一样, 调试的代码在localhost://下.
