### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by pierrebiver** [supnate/rekit#36]
Hello there,

your tools look really awesome, but I'm  using typescript for all my project right now.
Is it plan to have a typescript support someday?

**Comment by supnate** [comment]
Thanks @pierrebiver , there have been no plan to support typescript. Thanks.

**Comment by kencckw** [comment]
What is the minimal setup to support typescript?

**Comment by hosos** [comment]
Since we have already used TypeScript for development 2 years ago, it is great if the owner can Develop A TypeScript Version For Rekit.
@supnate

**Comment by supnate** [comment]
There's no minimal setup. Rekit heavily depends on [Babylon](https://github.com/babel/babylon) to parse ES6 so that it could refactor code (add, rename, delete), generate architecture. So it's not easy to support TypeScript.

**Comment by cocodrino** [comment]
maybe it's not so hard add [flow types ](https://flow.org) because it's incremental, I think than only would be necesary add the some files as library definitions in the code generation for actions and add some @flow pragmas...

**Comment by diegolaciar** [comment]
+1 for Typescript support. 

This tool is awesome !

Thanks Rekit team and supporters

**Comment by lucax88x** [comment]
@supnate 

As now CRA officially supports typescript, is there any plan on supporting ts? Should be out of the box.

**Comment by gaoxuerong** [comment]
+1 for Typescript support.

This tool is awesome !

Thanks Rekit team and supporters

**Comment by apperside** [comment]
It would be amazing if this tool could support Typescript
+1 for this feature

**Comment by danielo515** [comment]
Did anyone performed a migration to TS? I tried and wasted an entire day of work

**Comment by apperside** [comment]
+1 for typescript support

**Comment by Abbyzhoum** [comment]
+1 for typescript support
