### ISSUE TITLE
Using rekit behind corporate firewall

### ISSUE THREAD

**Issue by lucianlam** [supnate/rekit#37]
I apologize if this is not the right place or channel to ask this question.

I want to use rekit to create a project at work.  When I run the command:

rekit create <project_name>

I get a ETIMEDOUT error on connect.

Is there a setting I can use to set the proxy setting?

**Comment by supnate** [comment]
Rekit respects the proxy configuire in terminal. If you can access internet from terminal, Rekit should work.
