### ISSUE TITLE
Hot reload does not work anymore 

### ISSUE THREAD

**Issue by nelreina** [supnate/rekit#4]
getting this following error when starting a new project

I can't make hot reloading work at this time (No time to investigate). 

![screen shot 2016-09-09 at 19 32 52](https://cloud.githubusercontent.com/assets/5773049/18405892/3edf29ea-76c4-11e6-92a2-a73290804f56.png)

**Comment by nelreina** [comment]
The problem is **react-hot-loader version 3.0.0-beta!**  
After runing rekit - changed the version to **1.3.0** in package.json.

**Comment by supnate** [comment]
Hi @nelreina ,
Thanks for reporting and the investigation. I'm about to release a new version with some big improvements soon which will fix the issue.

It will fetch valid dependencies which have been verified instead of just using the latest versions.

**Comment by supnate** [comment]
Just published version v1.0.1 fixed this issue. Also created the Rekit website: http://rekit.js.org where you could find a sublime plugin to support Rekit😃

**Comment by nelreina** [comment]
@supnate Although this issue is resolved but react-hot-loader v1.3 have some issues that prevent me using redux-form [issue](https://github.com/erikras/redux-form/issues/1010). 

I will try to fix in my project and let you know what to do or create PR

**Comment by supnate** [comment]
Thanks @nelreina , React hot loader is still in beta so I didn't use it. Though it's quite stable now.
