### ISSUE TITLE
Yarn compatibility for production

### ISSUE THREAD

**Issue by ibLeo** [supnate/rekit#42]
Yarn works for dev builds but using `yarn build` returns the following error:
`100%
mv: no such file or directory: /Users/leo/work/mysite/build/static/main.js
Done: 14065.142ms
Couldn't parse bundle asset "/Users/leo/work/mysite/build/static/main.js".
Analyzer will use module sizes from stats file.`

There's no search results I can find on the matter and report.html has reams and reams of normal-looking results, AFAIK. As Far As I Can Tell, this is an inherent issue with using yarn with rekit.

**Comment by supnate** [comment]
Hi ibLeo, thank you for reporting this, it's a minor issue of the build script. This error doesn't affect anything but a un-well handled case for generating stat report.

**Comment by Simlesos** [comment]
rekit create app --sass
create webpack-config.js has an error, dist type scss rules should be sass-loader
```
{
  test: /\.scss$/,
  loader: isDev ? 'style-loader!css-loader?sourceMap!sass-loader?sourceMap'
            : 'style-loader!css-loader!sass-loader'
}
```

**Comment by JakeDluhy** [comment]
How is this minor? I don't have a `main.js` file, which means I don't have an app

**Comment by mscottford** [comment]
I had to add the presets to the babel config to resolve this issue:

```
          test: /\.jsx?$/,
          exclude: /node_modules|build/,
          loader: 'babel-loader?cacheDirectory=true',
          query: {
            presets: ['env', 'stage-0', 'react']
          }
```

**Comment by supnate** [comment]
Anyone could explain more on this? I've not been able to reproduce it for long time.

**Comment by aumeunier** [comment]
Have you tried packaging a project created with Rekit on an Ubuntu server for example ?
Basically, the "yarn build" runs completely and gives the following output:

```

Building, it may take a few seconds...
0% compiling
10% building modules
18.04% building modules
26.08% building modules
34.12% building modules
42.16% building modules
50.2% building modules
58.24% building modules
66.28% building modules
71% sealing
72% optimizing
73% basic module optimization
74% module optimization
75% advanced module optimization
76% basic chunk optimization
77% chunk optimization
78% advanced chunk optimization
79% module and chunk tree optimization
80% chunk modules optimization
81% advanced chunk modules optimization
82% module reviving
83% module order optimization
84% module id optimization
85% chunk reviving
86% chunk order optimization
87% chunk id optimization
88% hashing
89% module assets processing
90% chunk assets processing
91% additional chunk assets processing
91% additional asset processing
92% chunk asset optimization
94% asset optimization
100%

Couldn't parse bundle asset "[...]/build/static/main.js".
Analyzer will use module sizes from stats file.

Webpack Bundle Analyzer saved report to [...]/build/static/report.html
mv: no such file or directory: [...]/build/static/main.js
Done: 96855.161ms
Done in 100.50s.
```

Example of git status afterwards:
```
        modified:   build/index.html
        deleted:    build/static/bc54396771c64863193f7a3fe93d9cff.ttf
        deleted:    build/static/cbfd0298f008558557418d19abfc2f42.eot
        deleted:    build/static/dbf49360ba2857747beda5e7481c8fdf.svg
        deleted:    build/static/e31a701aa9b88125d36119acb8a10482.woff
        **deleted:    build/static/main.c6ec54afd7.js**
        modified:   build/static/report.html
```
index.html still links to `<script src="/static/main.cfee5a4d4f.js"></script>`

**Comment by mscottford** [comment]
I'm getting this behavior by running yarn and rekit inside of a Node Docker
container. I'll attempt to work up a repeatable example and publish it as a
simple repository.

**Comment by supnate** [comment]
Thanks @mscottford , that would be much helpful if there's a way to reproduce it.

**Comment by supnate** [comment]
Now Rekit creates apps by create-react-app, this issue should be gone.
