### ISSUE TITLE
"Missing class properties transform" when doing npm start

### ISSUE THREAD

**Issue by hpcsc** [supnate/rekit#46]
I just install latest version of rekit, create a sample app (with and without sass), do npm install and when run npm start, I have this error:

<img width="636" alt="screen shot 2017-08-31 at 10 28 23 am" src="https://user-images.githubusercontent.com/5293047/29903607-540d895c-8e37-11e7-9e36-b3bed88a3618.png">

If I change the presets for babel in package.json from:

<img width="261" alt="screen shot 2017-08-31 at 10 28 34 am" src="https://user-images.githubusercontent.com/5293047/29903634-75cf0dae-8e37-11e7-942a-ebfbd1e97faa.png">

to

<img width="155" alt="screen shot 2017-08-31 at 10 28 01 am" src="https://user-images.githubusercontent.com/5293047/29903641-7ee93284-8e37-11e7-890d-c796111c0164.png">

It's working normally. Just wondering any intended purpose for those presets? It's quite obvious error for me

**Comment by supnate** [comment]
I just verified that the default presets config section is:
```
"presets": [
    "es2015",
    "react",
    "babel-preset-stage-0"
]
```

Here `babel-preset-stage-0` just equals to `stage-0`. I'm not sure why you got the previous result. Could you please provide more information like node version, os?

**Comment by hpcsc** [comment]
I just tried again with `babel-preset-stage-0` and you are right, it's equivalent to `stage-0`

However the ordering of preset is important. When I first create the project, `babel-preset-stage-0` is at the beginning of the array. I need to shift it to second position in order for it to work

```
    "presets": [
      "es2015",
      "babel-preset-stage-0",
      "react"
    ]
```

**Comment by supnate** [comment]
Yes the presets order matters: https://babeljs.io/docs/plugins/#plugin-preset-ordering
I just don't know why you got the wrong order. I verified by re-installing Rekit and creating a new app, it's just correct.

**Comment by hpcsc** [comment]
i think it's due to node version. I change to node 6.11.2 and creation of site is ok, with presets in correct order
