### ISSUE TITLE
Missing class properties transform 

### ISSUE THREAD

**Issue by Danjavia** [supnate/rekit#5]
This error is launched when run npm start. some idea?

**Comment by Danjavia** [comment]
I solve the issue creating a .babelrc file with this.

```
{
  "presets": ["react", "es2015", "stage-0"],
  "env": {
    "development": {
      "plugins": [

      ]
    },
    "production": {
      "plugins": [

      ]
    }
  }
}

```

**Comment by supnate** [comment]
Hi @Danjavia , Rekit doesn't use a `.babelrc` file but use `package.json` to config babel instead. Do you run `npm start` under the Rekit itself or an app created by Rekit?

**Comment by Danjavia** [comment]
on app created with rekit.

**Comment by supnate** [comment]
@Danjavia , thank you for the prompt reply. I just re-installed Rekit from npm but couldn't re-produce the issue. Could you provide more info about your system? Such as mac/win, npm version?

**Comment by supnate** [comment]
By the way, do you have a `.babelrc` in some place above the app folder?

**Comment by Danjavia** [comment]
Not I use the .babelrc in the root of the project folder appname/.babelrc here.

**Comment by supnate** [comment]
It should work if there's no `.babelrc`. But if there's one at some point above the `appname` folder, it may have issue.

**Comment by Danjavia** [comment]
ok, but the appname folder in directly on home in my pc
