### ISSUE TITLE
Runing tests problems

### ISSUE THREAD

**Issue by rafaelfernandezgis** [supnate/rekit#50]
I'm getting this error in a clean installation.
Running tests:  tests\features\undefined\**\*.test.js ...
ERROR in ./node_modules/mocha-webpack/lib/webpack/includeFilesLoader.js?{"include":["C://Rafael//rekitTest//tests//before-all.js"]}!./.tmp/mocha-webpack/d1bd938075d032d4118117715de78aa6-entry.js

**Comment by supnate** [comment]
Thanks @rafaelfernandezgis for reporting this, it's a known issue of Rekit Portal when running all tests, will be fixed in the next release. You could use `npm test` command instead.

**Comment by rafaelfernandezgis** [comment]
Great Job Nate, I can't understand why people are not using this CLI massively. I think it's much better than create-react-app itself.

**Comment by supnate** [comment]
Thanks @rafaelfernandezgis . The fix has been published by Rekit Portal 2.0.6. You could use `npm install rekit-portal@2.0.6` to fix the issue.
