### ISSUE TITLE
Can you make a release

### ISSUE THREAD

**Issue by jeveloper** [supnate/rekit#60]
Hey there

great library but you've made some good changes for react 16 and id love to see a release published with recent commits 

Thanks

**Comment by supnate** [comment]
Thanks @jeveloper , I will make a release this week because there's some fixed needed for rekit-portal.

**Comment by jeveloper** [comment]
@supnate  Hey Nate 

I see you've added redux sage, that's great, i to use it in other projects. Would you be able to make a release so we can use it :)

thanks

**Comment by supnate** [comment]
It has been available as npm package `rekit-plugin-redux-saga`. See http://rekit.js.org/docs/plugin.html for more information about rekit plugin. You saw the change because I moved the plugin repo here.

**Comment by jeveloper** [comment]
Apologies , i was only looking at the release section 

thanks ! It's cool how you made this optional , plugins that is
