### ISSUE TITLE
how to config multi-level path?

### ISSUE THREAD

**Issue by kavinforever** [supnate/rekit#62]
Hi, i want to know is there any recommend config when meeting with multi-level apps,

such as : 
 /A1/B1/C1
/A1/B1/C2

/A1/B2/C3
/A1/B2/C4

/A2/B3/C5
/A2/B3/C6

C1-6 are all different pages,
A1,A2 as features or B1 B2 B3 as features?

thanks for answering.

**Comment by supnate** [comment]
Actually there aren't certain relationship between features and url paths. Features should be used used to organize elements by domains. Though usually pages under a feature starts with the same path. You can define nested router rules in `route.js`. Such as:
```
export default {
  path: 'A1',
  name: 'Home',
  childRoutes: [
    { name: 'B1', component: B1Page, childRoutes: [
        { path: 'C1', component: C1Page }
    ]},
  ],
};
```

**Comment by danielo515** [comment]
Will it be more consisten to split pages and features? I see it as a common root of confusion.
You will usually have one feature which is the app itself, but it's only responsibility it's to render the root page and the nested routes, hence it is not technically a feature.

Sorry for commenting on an old issue, but I think it is better than creating a new one for the same topic.
