### ISSUE TITLE
isIndex in route config is not handled correctly.

### ISSUE THREAD

**Issue by supnate** [supnate/rekit#65]

**Comment by masummillat** [comment]
Nothing  specific . i think you are facing a rendering problem of a specific route. 
ex: http://localhost:6075/contact/ 
Page not found
 if it is the problem then just add a  "/" in path of route.js
ex: 
 path: '/contact',
  name: 'Contact',
  childRoutes: [
    { path: 'default-page', name: 'Default page', component: DefaultPage, isIndex: true },
  ],

**Comment by supnate** [comment]
Fixed by https://github.com/supnate/rekit-boilerplate/commit/47c4871b90dd4d8d4a3a85713d173bb9c41d6db3 .
