### ISSUE TITLE
Documentation update for SASS support

### ISSUE THREAD

**Issue by edcala** [supnate/rekit#67]
Hi,

Just a heads up for anyone running Rekit with SASS that there is a step missing in the Readme.md.
After creating a new application with: `rekit create <app-name> [--sass]`
the extra step is to modify line 14 in package.json, rekit.css = "sass": 

```
{
    ...
    "rekit": {
        ...
        "css": "sass"
    }
    ...
}
```

After that you can proceed to run the Rekit server: `npm start`

Cheers

**Comment by supnate** [comment]
Thanks @edcala for reporting this! Now it has been fixed in the template. No need to update anything. New created sass apps will have been fixed.
