### ISSUE TITLE
自动生成的代码,和自己写的代码缩进量不一样,能不能改成通用的手写缩进量

### ISSUE THREAD

**Issue by chowsource** [supnate/rekit#70]
![image](https://user-images.githubusercontent.com/5119971/35382773-3d908f84-01fb-11e8-889a-d50348c1a6ab.png)

**Comment by supnate** [comment]
什么场景会不一样？如果不一样是 bug，要修。

**Comment by chowsource** [comment]
不是bug,自动生成代码默认tab缩进量是2个空格,但intellij idea 默认是4个空格

**Comment by supnate** [comment]
哦，了解，Rekit 使用2个空格（不是Tab）作为代码缩进，这个代码风格是不可自定义的。你只能修改 intelij 的相关设置。

**Comment by chowsource** [comment]
后续升级能改成4个空格缩进量吗,毕竟intellij默认4个空格,更加通用

**Comment by supnate** [comment]
暂不考虑。2个空格作为缩进是更通用的风格。
