### ISSUE TITLE
Document existing project migration

### ISSUE THREAD

**Issue by andreasciamanna** [supnate/rekit#73]
I can't seem to find a dedicated ticket for it.

I just started developing with React+Redux, and I already have some code written.

I'd really like to try Rekit with my project, but I have no idea how to make it ”Rekit compliant”.

Updating the documentation with directions on how to do that would give a lot of help.

**Comment by davidnagli** [comment]
+1

**Comment by Slapbox** [comment]
Is there a plan to add documentation for this? Rekit seems VERY worth switching to, but right now there's just not enough info to warrant embarking on that project.

**Comment by supnate** [comment]
Yeah, I will write one as promised. The basic sample will be migrating Reudx's TodoMVC app to Rekit: https://github.com/supnate/rekit-todomvc . Also wish you could give more information of your projects.

**Comment by Slapbox** [comment]
Thanks very much for the update and for all the hard work you've already done! My project is based on [Electron React Boilerplate](https://github.com/chentsulin/electron-react-boilerplate), just to give a little info.

**Comment by Slapbox** [comment]
@supnate is there any major issue you can see with using Rekit with Electron, if you are familiar?

**Comment by supnate** [comment]
Sure, Rekit works fine with Electron just like other React projects. I once created an app: https://github.com/supnate/command-pad based on Electron and Rekit.

**Comment by supnate** [comment]
Done: https://medium.com/@nate_wang/using-rekit-studio-in-an-existing-react-project-39713d9667b

**Comment by Slapbox** [comment]
@supnate you are the man!

I'm excited to give this a try. Will report back in a few days when I've had a chance to give it a try.

**Comment by Slapbox** [comment]
Hey @supnate thanks for writing this up. I got delayed for quite a while on reviewing it.

The setup involved for an existing project that is rather far along in development is a bit more involved than I expected.

While there's a lot of features I'd really like to take advantage of, the one I'm most interested in is the code visualization feature. Is there some way to take advantage of that feature of Rekit without getting too involved in reworking my project's architecture?

Thanks again for your great work.
