### ISSUE TITLE
Migrate test suite from Mocha to Jest

### ISSUE THREAD

**Issue by jkomyno** [supnate/rekit#77]
Many React developers are used to Jest, since it's another OSS product mantained by Facebook, and since it's the default option in new RN Projects or in [create-react-app](https://github.com/facebook/create-react-app).
Mocha requires to manually import the various expect and assert libraries, which may be a pain.
Also, Jest configuration' extension capabilities are almost limitless.

**Comment by supnate** [comment]
Yeah thanks for the suggestion! There will be plugin to support that!
