### ISSUE TITLE
Can ESLint integrate with Rekit Studio?

### ISSUE THREAD

**Issue by DanPen** [supnate/rekit#79]
First off, let me say that thank you for an amazing product/development experience.

Would it be possible to allow custom ESLint configurations? I personally don't like coding with semi-colons in JS. I tried adding `"semi": 2` to the `.eslintrc` file that gets generated, but I don't seem to see any errors in Rekit Studio.

Thanks for any insight.

**Comment by supnate** [comment]
Thanks @DanPen , it has not been supported yet. But has been in our backlog. Stay tuned.

**Comment by Prattjames** [comment]
Hi @DanPen,

Since the last release of Rekit-Studio and Rekit-Core the Eslint custom configuration is now available,
just update your packages.

Best Regards

**Comment by supnate** [comment]
Thanks @Prattjames for the update! Just forgot to mark this resolved!
