### ISSUE TITLE
Creating or Deleting a Component causes issues on route.js

### ISSUE THREAD

**Issue by graphy21** [supnate/rekit#92]
When I create or delete component with url path in rekit-studio, the below comment lines on the top in "route.js" flie is doubled.

// This is the JSON way to define React Router rules in a Rekit app.
// Learn more from: http://rekit.js.org/docs/routing.html

**Comment by supnate** [comment]
Thanks @graphy21 for reporting this! It's now fixed by https://github.com/supnate/rekit/commit/2f0ebf803e0b45580bf4bafbbdafeff818df96c8 .
Update to rekit-core@2.2.3 in your project to fix the issue.
