### ISSUE TITLE
Failed to load project data

### ISSUE THREAD

**Issue by benavent** [supnate/rekit#98]
First off - Rekit is a great idea, was really loving it for about half an hour, then...

The studio tab crashed saying: 
"Failed to load project data. Request failed with status code 500"

I have restarted the server and the browser to no effect.

Help...

![screen shot 2018-03-02 at 17 38 37](https://user-images.githubusercontent.com/16837199/36913105-c0ab9bbe-1e40-11e8-9a41-6fcd06f2afbd.png)

**Comment by zeroxx1986** [comment]
Do you use Windows by any chance, and tried moving / deleting a Feature while the development server was running?

**Comment by supnate** [comment]
Please tell the Rekit Studio version, os, network error detail since it’s a 500 error

**Comment by Isabellle** [comment]
I have the same issue, and deleted features while dev server was running

**Comment by benavent** [comment]
using: macOS 10.13.3 & Chrome 64.0.3282.167

Rekit version from package.json:
"rekit-core": "^2.1.1",
"rekit-studio": "^2.2.0",

I could not find any further detail on the error. 
Nothing in the Chrome console or on the terminal.

I think I deleted a feature.

In the end I deleted the whole project and restarted and it seem to be working at the moment.

**Comment by supnate** [comment]
Please update rekit studio and core to the latest version
